version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
  web:
    build: ../../
    command: bundle exec rails s -b 3000 -b 0.0.0.0
    volumes:
      - ../../:/seeds-house
    ports:
      - "3000:3000"
    depends_on:
      - db