default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: seeds_house_development
  username: postgres
  password: postgres
  host: db

test:
  <<: *default
  database: seeds_house_test
  username: postgres
  password: postgres
  host: db

server: &server
  <<: *default
  host: <%= ENV["POSTGRESQL_HOST"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  database: <%= ENV["POSTGRESQL_DB"] %>

staging:
  <<: *server

production:
  <<: *server
