default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: seeds_house_development
  username: postgres
  password: postgres
  host: db

test:
  <<: *default
  database: seeds_house_test
  username: postgres
  password: postgres
  host: db

staging:
  <<: *default
  host: <%= ENV["POSTGRESQL_HOST"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  database: <%= ENV["POSTGRESQL_DB"] %>

production:
  <<: *default
  database: seeds_house_production
  username: seeds_house
  password: <%= ENV['SEEDS_HOUSE_DATABASE_PASSWORD'] %>
